name: hotel_booking_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # dio: ^4.0.6
  # faker: ^2.1.0
  flutter:
    sdk: flutter
    
  # flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.0+1
  go_router: ^6.0.4
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    

